FROM node:20-alpine

RUN npm i -g pnpm

# Set the working directory
WORKDIR /cronJob

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Start the app using bun
CMD ["pnpm", "run", "start"]