FROM node:slim

RUN apt-get update -y && apt-get install -y openssl

RUN npm install -g bun

# Set the working directory
WORKDIR /orchestrator

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY prisma ./prisma

# Install dependencies
RUN bun install
RUN bun run db:client

# Copy the rest of the application code
COPY . .

# Start the Next.js app
CMD ["bun", "run", "start"]
