services:
  tester-api:
    container_name: api-tester
    build: 
    environment:
      DEBUG: "true"
      ZAP_BASE_URL: "http://zap:8080"
      ZAP_DEPTH_SCAN: "true"
    ports:
      - "5000:5000"
    volumes:
      - "./server:/app/server"
    depends_on:
      - zap

  zap:
    image: zaproxy/zap-stable
    user: zap
    ports:
      - "8080:8080"
    command:
      [
        "zap.sh",
        "-daemon",
        "-host",
        "0.0.0.0",
        "-port",
        "8080",
        "-config",
        "api.disablekey=true",
        "-config",
        "api.addrs.addr.name=.*",
        "-config",
        "api.addrs.addr.regex=true",
      ]
    restart: unless-stopped