FROM node:20-alpine

RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY prisma ./prisma

# Install dependencies
RUN pnpm install
RUN pnpm run db:client

# Copy the rest of the application code
COPY . .

RUN mkdir -p ./src/openapiSpec/openApi

# Expose the port the Next.js app listens on
EXPOSE 3000

# Start the Next.js app
CMD ["pnpm", "run", "docker:start", "-p", "3000"]
