services:
  zap:
    image: zaproxy/zap-stable
    container_name: owasp_zap
    ports:
      - "8080:8080"
    environment:
      ZAP_API_KEY: abc123abc
    command:
      - zap.sh
      - -daemon
      - -host
      - 0.0.0.0
