services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Orchestrator
    container_name: test-orchestrator
    environment:
      - DATABASE_URL="postgres://secura:password@localhost:5432/db"
      - PORT=3005
    ports:
      - 3005:3005