FROM node:20-alpine

RUN npm install -g pnpm

# Set the working directory
WORKDIR /orchestrator

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY prisma ./prisma

# Install dependencies
RUN pnpm install
RUN pnpm run db:client

# Copy the rest of the application code
COPY . .

EXPOSE 3005

# Start the Next.js app
CMD ["pnpm", "run", "start"]
