FROM oven/bun:alpine

# Set the working directory
WORKDIR /orchestrator

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN bun install

# Copy the rest of the application code
COPY . .

# Start the app using bun
CMD ["bun", "run", "start"]